### ISSUE TITLE
I created a "farm" called Eve's Orchard

### ISSUE THREAD

**Issue by lindseyberk** [heartdeco/addison-county-community-table#15]
But it is not showing up in the list - does it need to be approved? I clicked away from it and can't find it.

**Comment by justindoran** [comment]
Hi Lindsey! Great name and description.😂 It shows up at the bottom of the list (as they currently appear in order of creation):
https://secure-depths-72680.herokuapp.com/farms/44

Just a heads up: early next week, after our next project update, we'll be migrating to a new testing environment and server at a less mysterious-sounding url.

**Comment by justindoran** [comment]
Also, it makes sense that you should be able to find your own businesses in your account sidebar, doesn't it? I'll put that on the docket for the next release.
