### ISSUE TITLE
"Farms" page not working in menu

### ISSUE THREAD

**Issue by lindseyberk** [heartdeco/addison-county-community-table#7]
**Describe the bug**
I tried clicking on "Farms" in the top left menu to get started and nothing happened. The only thing I can do in the testing environment is click on Learn More or go to the About page.

**To Reproduce**
1. Go to top left menu
2. Click on Farms

**Expected behavior**
Take me to the Farms page.

**Desktop (please complete the following information):**
 - OS: Mojave 10.14.6
 - Browser: Firefox 
 - Version: 78.0.2

**Comment by justindoran** [comment]
Hi Lindsey! Thanks for creating an issue﻿—glad the system is working!

We're working on that functionality right now and should be able to push it to the testing environment this evening. I'll update this issue again when we do.

**Comment by justindoran** [comment]
Hi again Lindsey: quick update, we got the farm-specific list and interface implemented, but it needs to go through our code review process before we push it to the testing environment. We'll be able to review it tomorrow morning and put it up for you by around noon tomorrow (Thurs. July 22), hopefully earlier. I'll update this again when it's online!

**Comment by justindoran** [comment]
We've just pushed the new farm and restaurant distinct interfaces to the testing environment (they're still very similar right now). Check it out at: [https://secure-depths-72680.herokuapp.com/farms](https://secure-depths-72680.herokuapp.com/farms)

I also added some randomly-generated Farm and Restaurant data so you can see what things look like when they're filled out a bit. And I went ahead and gave your user permission to create new businesses—you can find that feature in the user drawer in the upper right. So now you can create your own farm (or restaurant) on the platform.

**Comment by lindseyberk** [comment]
Thanks Justin I’m heading on vacation after tomorrow through Wednesday so I’ll be able to take a look next week. I’ll forward to the Board as well.

**Comment by justindoran** [comment]
>  I’m heading on vacation after tomorrow through Wednesday 

Have a great vacation!
