### ISSUE TITLE
I added menu items and a bar showed up saying it was added to my basket. However there is no basket that I can see.

### ISSUE THREAD

**Issue by RBCarter2020** [heartdeco/addison-county-community-table#9]
**Is your feature request related to a need you have or imagine others having? Please describe.**
A clear and concise description of the need. Ex. As a business owner, I need [...]

**Describe the solution you think would fulfill this need**

**Additional context**
Add any other context or sketches about the feature request here.

**Comment by mfgallagher** [comment]
We will have a visible basket for you by the end of the week!

**Comment by justindoran** [comment]
The preliminary functionality for the shopping cart is available on the testing environment now. Removing items from the cart and going through the checkout process should be on the testing environment early next week.
